name: Verify Saucelabs

on: pull_request

jobs:
  verify-saucelabs:
    name: Verify Sauce Labs

    # Run only from the original repository
    # Because this job requires secrets, which cannot be shared with forks
    if: github.event.pull_request.head.repo.full_name == github.repository

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node 16
        uses: actions/setup-node@v3
        env:
          FORCE_COLOR: 0
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build packages
        run: yarn build

      - name: Test
        run: |
          cd packages/test-runner-saucelabs
          yarn test
        env:
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
